apps/perfiles/urls.py
from django.conf.urls import url


urlpatterns = [
  	url(r'^$', 'apps.perfiles.views.alumno', name='alumno'),   	
   	url(r'^addAlumno$', 'apps.perfiles.views.addAlumno', name='addAlumno'),
   	url(r'^alumno/upd/(?P<id>\d+)$', 'apps.perfiles.views.updAlumno', name='updAlumno'),
    url(r'^alumno/del/(?P<id>\d+)$', 'apps.perfiles.views.delAlumno', name='delAlumno'),

   	url(r'^profesor$','apps.perfiles.views.profesor',name='profesor'),
   	url(r'^profesor/add$', 'apps.perfiles.views.addProfesor', name='addProfesor'),
    url(r'^profesor/upd/(?P<id>\d+)$', 'apps.perfiles.views.updProfesor', name='updProfesor'),    
    url(r'^profesor/del/(?P<id>\d+)$', 'apps.perfiles.views.delProfesor', name='delProfesor'),
   	
   	url(r'^encargado$', 'apps.perfiles.views.encargado', name='encargado'),
   	url(r'^encargado/add$','apps.perfiles.views.addEncargado', name='addEncargado'),
   	url(r'^encargado/upd/(?P<id>\d+)$', 'apps.perfiles.views.updEncargado', name='updEncargado'),     
    url(r'^encargado/del/(?P<id>\d+)$', 'apps.perfiles.views.delEncargado', name='delEncargado'),


]

matricula/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'django.contrib.auth.views.login', {'template_name':'index.html'}, name='login'),
    url(r'^main/', include('apps.matricula.urls')),
    url(r'^matricula/', include('apps.matricula.urls', namespace='matricula_app')),
    url(r'^perfiles/', include('apps.perfiles.urls', namespace='perfiles_app')),
    url(r'^cerrar/$', 'django.contrib.auth.views.logout_then_login',name='logout'),
    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
]

apps/perfiles/models.py
# coding: utf-8
from django.db import models
#from django.contrib.auth.models import User


class Encargado(models.Model):

    ECV = [
        ('Soltero', 'Soltero(a)'),
        ('Casado', 'Casado(a)'),
        ('Viudo', 'Viudo(a)'),
    ]
    SEX = [
        ('M', 'Padre'),
        ('F', 'Madre'),
    ]
    nombres = models.CharField(max_length=50, unique=True)
    apellidos = models.CharField(max_length=60)
    dni = models.CharField(max_length=8, unique=True)
    sexo = models.CharField(choices=SEX, max_length=10,
                            blank=True, verbose_name='Encargado')
    direccion = models.CharField(max_length=100)
    estado_civil = models.CharField(choices=ECV, max_length=10, blank=True, verbose_name='Estado_civíl')
    telefono = models.CharField(max_length=13)
    email = models.EmailField(max_length=50)
    ocupacion = models.CharField(max_length=40)

    def __str__(self):
        return u"%s %s" % (self.nombres, self.apellidos)


class Alumno(models.Model):
    SEX = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ]
    #usuario = models.OneToOneField(User)
    nombres = models.CharField(max_length=50, unique=True)
    apellidos = models.CharField(max_length=60)
    dni = models.CharField(max_length=8, unique=True)
    sexo = models.CharField(choices=SEX, max_length=10,
                            blank=True, verbose_name='Género')
    fecha_nac = models.DateTimeField(auto_now=True)
    lugar_nac = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)
    provincia = models.CharField(max_length=100)
    telefono = models.CharField(max_length=13)
    email = models.EmailField(max_length=100)
    imagen = models.ImageField(upload_to='alumnos')  # falta hacer algo
    encargado = models.ForeignKey(Encargado)

    # def __unicode__(self):
    #     return self.nombres
    def __str__(self):
        return u"%s %s" % (self.nombres, self.apellidos)


class Profesor(models.Model):

    nombres = models.CharField(max_length=50, unique=True)
    apellidos = models.CharField(max_length=60)
    dni = models.CharField(max_length=8, unique=True)
    direccion = models.CharField(max_length=100)
    especialidad = models.CharField(max_length=30)
    telefono = models.CharField(max_length=13)
    fecha_nac = models.DateTimeField(verbose_name='Fecha nacimiento')
    imagen = models.ImageField(upload_to='profesores')  # falta hacer algo

    def __str__(self):
        return u"%s %s" % (self.nombres, self.apellidos)

apps/perfiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Alumno, Encargado, Profesor


class AlumnoForm(forms.ModelForm):
	class Meta:
		model=Alumno
		exclude=()
		widgets={
		#'usuario':forms.TextInput(attrs={'class':'form-control'}),
		'nombres':forms.TextInput(attrs={'class':'form-control'}),
		'apellidos':forms.TextInput(attrs={'class':'form-control'}),
		'dni':forms.TextInput(attrs={'class':'form-control'}),
		'lugar_nac':forms.TextInput(attrs={'class':'form-control'}),
		'direccion':forms.TextInput(attrs={'class':'form-control'}),
		'ciudad':forms.TextInput(attrs={'class':'form-control'}),
		'provincia':forms.TextInput(attrs={'class':'form-control'}),
		'telefono':forms.TextInput(attrs={'class':'form-control'}),
		'email':forms.TextInput(attrs={'class':'form-control'}),
		#'imagen':forms.FileInput(attrs={'class':'btn btn-warning'}),
		}
		
class EncargadoForm(forms.ModelForm):
	class Meta:
		model=Encargado
		exclude=()
		widgets={
		'nombres':forms.TextInput(attrs={'class':'form-control'}),
		'apellidos':forms.TextInput(attrs={'class':'form-control'}),
		'dni':forms.TextInput(attrs={'class':'form-control'}),
		'direccion':forms.TextInput(attrs={'class':'form-control'}),
		'telefono':forms.TextInput(attrs={'class':'form-control'}),
		'email':forms.EmailInput(attrs={'class':'form-control'}),
		'ocupacion':forms.TextInput(attrs={'class':'form-control'}),
		}
		
class ProfesorForm(forms.ModelForm):
	class Meta:
		model=Profesor
		exclude=()
		
	

apps/perfiles/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy, reverse
from django.template import RequestContext
from .models import Alumno, Encargado, Profesor
from .forms import AlumnoForm, EncargadoForm, ProfesorForm


#@login_required
def alumno(request):
	lista=Alumno.objects.all()
	numreg=lista.count()
	return render(request,'perfiles/alumno.html',{'lista':lista,'cantidad':numreg})

def addAlumno(request):
	if request.method=='POST':
		objform=AlumnoForm(request.POST, request.FILES)
		if objform.is_valid():
			objform.save()
			return redirect(reverse('perfiles_app:alumno'))
	else:
		objform=AlumnoForm()
	return render(request,'perfiles/addAlumno.html', {'form':objform})	

def updAlumno(request, id):
	obj_edit=Alumno.objects.get(pk=id)
	if request.method=='POST':
		objform=AlumnoForm(request.POST, instance=obj_edit) #oojo
		if objform.is_valid():
			objform.save()
			return redirect(reverse('perfiles_app:alumno'))
	else:
		objform=AlumnoForm(instance=obj_edit)
	return render(request, 'perfiles/updAlumno.html', {'form': objform}, context_instance=RequestContext(request))

def delAlumno(request, id, template_name='perfiles/delAlumno.html'):
	objdel=Alumno.objects.get(pk=id)
	if request.method=='POST':
		objdel.delete()
		return redirect(reverse('perfiles_app:alumno'))	
	return render(request, template_name,{'object':objdel})


def encargado(request):
	lista=Encargado.objects.all()
	numreg=lista.count()
	return render(request,'perfiles/encargado.html',{'lista':lista,'cantidad':numreg})

def addEncargado(request):
	if request.method=='POST':
		objform=EncargadoForm(request.POST, request.FILES)
		if objform.is_valid():
			objform.save()
			return redirect(reverse('perfiles_app:encargado'))
	else:
		objform=EncargadoForm()
	return render(request,'perfiles/addEncargado.html', {'form':objform})	

#@login_required
def updEncargado(request, id):
	obj_edit=Encargado.objects.get(pk=id)
	if request.method=='POST':
		formulario=EncargadoForm(request.POST, instance=obj_edit)
		if formulario.is_valid():
			formulario.save()
			return redirect(reverse('perfiles_app:encargado'))
	else:
		formulario=EncargadoForm(instance=obj_edit)
	return render(request,'perfiles/updEncargado.html', {'form':formulario},context_instance = RequestContext(request))

#@login_required	
def delEncargado(request, id, template_name='perfiles/delEncargado.html'):
    obj_delete = Encargado.objects.get(pk=id)    
    if request.method=='POST':
        obj_delete.delete()
        return redirect(reverse('perfiles_app:encargado'))
    return render(request, template_name, {'object':obj_delete})

def profesor(request):
	lista=Profesor.objects.all()
	numreg=lista.count()
	return render(request,'perfiles/profesor.html',{'lista':lista,'cantidad':numreg})

def addProfesor(request):
	if request.method=='POST':
		objform=ProfesorForm(request.POST, request.FILES)
		if objform.is_valid():
			objform.save()
			return redirect(reverse('perfiles_app:profesor'))
	else:
		objform=ProfesorForm()
	return render(request,'perfiles/addProfesor.html', {'form':objform})
	
def updProfesor(request, id):
	obj_edit=Profesor.objects.get(pk=id)
	if request.method=='POST':
		formulario=ProfesorForm(request.POST, instance=obj_edit)
		if formulario.is_valid():
			formulario.save()
			return redirect(reverse('perfiles_app:profesor'))
	else:
		formulario=ProfesorForm(instance=obj_edit)
	return render(request,'perfiles/updProfesor.html', {'form':formulario},context_instance = RequestContext(request))

def delProfesor(request, id, template_name='perfiles/delProfesor.html'):
    obj_delete = Profesor.objects.get(pk=id)    
    if request.method=='POST':
        obj_delete.delete()
        return redirect(reverse('perfiles_app:profesor'))
    return render(request, template_name, {'object':obj_delete})

templates/perfiles/addAlumno.html
{% extends "base.html" %}
{% block titulo %}
	Regitrar Alumno
{% endblock titulo %}
{% block contenido %}
<div class="page-header">
	<h4>
		<a href="{% url 'perfiles_app:alumno' %}" class="btn btn-warning">
			<span class="glyphicon glyphicon-chevron-left"></span>Regresar
		</a>
		<b>Datos del alumno</b>
	</h4>
</div>
<div>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit/button" class="btn btn-success pull-right">Registrar<span class="glyphicon glyphicon-chevron-right"></span></button>

		<a id="opciones"><span class="glyphicon glyphicon-chevron-right"> Más opciones</span></a><br>
		<a id="opcion1" href="{% url 'perfiles_app:encargado' %}"><span class="glyphicon glyphicon-plus"> Gestion encargados</span></a><br>
	</form>
</div><br><br><br>
{% endblock contenido %}
{% block mijs %}
	<script>
	$(document).ready(function(){	    
	    $("#opcion1").hide();
	    $("#opciones").click(function(){
		    $("#opcion1").toggle();
		});	
	});
	</script>
{% endblock mijs %}

templates/perfiles/addEncargado.html
{% extends "base.html" %}
{% block titulo %}
	Regitrar apoderado
{% endblock titulo %}
{% block contenido %}
<div class="page-header">
	<h4>
		<a href="{% url 'perfiles_app:encargado' %}" class="btn btn-warning">
			<span class="glyphicon glyphicon-chevron-left"></span>Regresar
		</a>
		<b>Datos del apoderado</b>
	</h4>
</div>
<div>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit/button" class="btn btn-success pull-right">Registrar<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>
</div><br><br><br>
{% endblock contenido %}

templates/perfiles/addProfesor.html
{% extends "base.html" %}
{% block titulo %}
	Regitrar profesor
{% endblock titulo %}
{% block contenido %}
<div class="page-header">
	<h4>
		<a href="{% url 'perfiles_app:profesor' %}" class="btn btn-warning">
			<span class="glyphicon glyphicon-chevron-left"></span>Regresar
		</a>
		<strong>Datos del profesor</strong>
	</h4>
</div>
<div class="page-header">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit/button" class="btn btn-success pull-right">Registrar<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>
</div><br>
{% endblock contenido %}

templates/perfiles/alumno.html
{% extends "base.html" %}
{% block titulo %}
	Alumno
{% endblock titulo %}
{% block contenido %}
<div class="page-header">
	<h4>
		<b>Tienes <span class="label label-warning">{{cantidad}}</span> alumno(s) registrado(s) </b>
		<a href="{% url 'perfiles_app:addAlumno' %}" class="btn btn-primary pull-right">
			<span class="glyphicon glyphicon-plus">Nuevo registro</span>
		</a>
	</h4>
</div><!-- page-header -->

<div>
	<table class="table table-striped table-condenced table-hover">
		<thead>
			<tr>
				<th>Nombres</th>
			    <th>Apellidos</th>
			    <th>Sexo</th>
			    <th>Direccion</th>
			    <th>Telefono</th>
			    <th>Encargado</th>
			    <th>Opciones</th>
			</tr>
		</thead>
		<tbody>
		{% for alumno in lista %}		
			<tr>
				<td>{{alumno.nombres}}</td>
				<td>{{alumno.apellidos}}</td>
				<td>{{alumno.sexo}}</td>
				<td>{{alumno.direccion}}</td>
				<td>{{alumno.telefono}}</td>
				<td>{{alumno.encargado}}</td>
				<td>
					<a href="#" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-book"></span></a>
					<a href="{% url 'perfiles_app:updAlumno' alumno.pk %}" class="btn btn-warning btn-xs"> <span class="glyphicon glyphicon-pencil"></span></a>
					<a href="{% url 'perfiles_app:delAlumno' alumno.pk %}" class="btn btn-danger btn-xs"> <span class="glyphicon glyphicon-trash"></span></a>
				</td>
			</tr>	
		{% endfor %}
		</tbody>	
	</table>
</div>
{% endblock contenido %}

templates/perfiles/delAlumno.html
{% extends "base.html" %}
{% block title %}
	Confirma eliminar
{% endblock title %}
{% block contenido %}
<div class="page-header">
		<h4>
			<a href="{% url 'perfiles_app:alumno' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Confirma eliminar</b>
		</h4>
	</div>
	<form method="POST">{% csrf_token %}
		<div class="alert alert-danger">
		<span class="glyphicon glyphicon-exclamation-sign"></span>
		  <b>Cuidado!</b> Estas seguro de querer eliminar a: "<strong>{{ object }}</strong>" ?
		</div>		
			<button type="submit/button" class="btn btn-success pull-right">Estoy seguro<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>	

{% endblock contenido %}

templates/perfiles/delEncargado.html
{% extends "base.html" %}
{% block title %}
	Confirma eliminar
{% endblock title %}
{% block contenido %}
<div class="page-header">
		<h4>
			<a href="{% url 'perfiles_app:encargado' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Confirma eliminar</b>
		</h4>
	</div>
	<form method="POST">{% csrf_token %}
		<div class="alert alert-danger">
		<span class="glyphicon glyphicon-exclamation-sign"></span>
		  <b>Cuidado!</b> Estas seguro de querer eliminar el: "<strong>{{ object }}</strong>" ?
		</div>		
			<button type="submit/button" class="btn btn-success pull-right">Estoy seguro<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>	

{% endblock contenido %}

templates/perfiles/delProfesor.html
{% extends "base.html" %}
{% block title %}
	Confirma eliminar
{% endblock title %}
{% block contenido %}
<div class="page-header">
		<h4>
			<a href="{% url 'perfiles_app:profesor' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Confirma eliminar</b>
		</h4>
	</div>
	<form method="POST">{% csrf_token %}
		<div class="alert alert-danger">
		<span class="glyphicon glyphicon-exclamation-sign"></span>
		  <b>Cuidado!</b> Estas seguro de querer eliminar a: "<strong>{{ object }}</strong>" ?
		</div>		
			<button type="submit/button" class="btn btn-success pull-right">Estoy seguro<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>	

{% endblock contenido %}

templates/perfiles/encargado.html
{% extends "base.html" %}
{% block titulo %}
	Apoderado
{% endblock titulo %}
{% block contenido %}
<div class="page-header">
	<h4>
		<b>Tienes <span class="label label-warning">{{cantidad}}</span> apoderado(s) registrado(s) </b>
		<a href="{% url 'perfiles_app:addEncargado' %}" class="btn btn-primary pull-right">
			<span class="glyphicon glyphicon-plus">Nuevo registro</span>
		</a>
	</h4>
</div><!-- page-header -->

<div>
	<table class="table table-striped table-condenced table-hover">
		<thead>
			<tr> 
				<th>Nombres</th>
			    <th>Apellidos</th>
			    <th>DNI</th>
			    <th>Direccion</th>
			    <th>Telefono</th>
			    <th>Opciones</th>
			</tr>
		</thead>
		<tbody>
		{% for encargado in lista %}		
			<tr>
				<td>{{encargado.nombres}}</td>
				<td>{{encargado.apellidos}}</td>
				<td>{{encargado.dni}}</td>
				<td>{{encargado.direccion}}</td>
				<td>{{encargado.telefono}}</td>
				<td>
					<a href="" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-book"></span></a>
					<a href="{% url 'perfiles_app:updEncargado' encargado.pk %}" class="btn btn-warning btn-xs"> <span class="glyphicon glyphicon-pencil"></span></a>
					<a href="{% url 'perfiles_app:delEncargado' encargado.pk %}" class="btn btn-danger btn-xs"> <span class="glyphicon glyphicon-trash"></span></a>
				</td>
			</tr>	
		{% endfor %}
		</tbody>	
	</table>

</div>
{% endblock contenido %}

templates/perfiles/profesor.html
{% extends "base.html" %}
{% block titulo %}
	profesor
{% endblock titulo %}
{% block contenido %}
<div class="page-header">
	<h4>
		<b>Tienes <span class="label label-warning">{{cantidad}}</span> profesor(es) registrado(s) </b>
		<a href="{% url 'perfiles_app:addProfesor' %}" class="btn btn-primary pull-right">
			<span class="glyphicon glyphicon-plus">Nuevo registro</span>
		</a>
	</h4>
</div><!-- page-header -->

<div>
	<table class="table table-striped table-condenced table-hover">
		<thead>
			<tr>
				<th>Nombres</th>
			    <th>Apellidos</th>
			    <th>DNI</th>
			    <th>Direccion</th>
			    <th>Especialidad</th>
			    <th>Telefono</th>
			    <th>Fecha Nacimiento</th>
			    <th>Opciones</th>
			</tr>
		</thead>
		<tbody>
		{% for profesor in lista %}		
			<tr>
				<td>{{profesor.nombres}}</td>
				<td>{{profesor.apellidos}}</td>
				<td>{{profesor.dni}}</td>
				<td>{{profesor.direccion}}</td>
				<td>{{profesor.especialidad}}</td>
				<td>{{profesor.telefono}}</td>
				<td>{{profesor.fecha_nac}}}</td>
				<td>
					<a href="#" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-book"></span></a>
					<a href="{% url 'perfiles_app:updProfesor' profesor.pk %}" class="btn btn-warning btn-xs"> <span class="glyphicon glyphicon-pencil"></span></a>
					<a href="{% url 'perfiles_app:delProfesor' profesor.pk%}" class="btn btn-danger btn-xs"> <span class="glyphicon glyphicon-trash"></span></a>
				</td>
			</tr>	
		{% endfor %}
		</tbody>	
	</table>
</div>
{% endblock contenido %}

templates/perfiles/updAlumno.html
{% extends "base.html" %}
{% block title %}
	Actualizar
{% endblock title %}
{% block contenido %}
	<div class="page-header">
		<h4>
			<a href="{% url 'perfiles_app:alumno' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Actualizar alumno</b>
		</h4>
	</div>
	<div>
		<form method="POST">{% csrf_token %}
			{{form.as_p}}
			 <button type="submit/button" class="btn btn-success pull-right">Guardar cambios<span class="glyphicon glyphicon-chevron-right"></span></button>
			 <a id="opciones"><span class="glyphicon glyphicon-chevron-right"> Más opciones</span></a><br><br>
			<a id="opcion1" href="{% url 'perfiles_app:encargado' %}"><span class="glyphicon glyphicon-plus"> Gestionar encargados</span></a><br>
		</form>
	</div><br><br><br>
{% endblock contenido %}
{% block mijs %}
	<script>
	$(document).ready(function(){	    
	    $("#opcion1").hide();
	    $("#opciones").click(function(){
		    $("#opcion1").toggle();
		});	
	});
	</script>
{% endblock mijs %}

templates/perfiles/updEncargado.html
{% extends "base.html" %}
{% block title %}
	Actualizar
{% endblock title %}
{% block contenido %}
	<div class="page-header">
		<h4>
			<a href="{% url 'perfiles_app:encargado' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Actualizar Encargado</b>
		</h4>
	</div>
	<div>
		<form method="POST">{% csrf_token %}
			{{form.as_p}}
			 <button type="submit/button" class="btn btn-success pull-right">Guardar cambios<span class="glyphicon glyphicon-chevron-right"></span></button>
		</form>
	</div><br><br><br>
{% endblock contenido %}

templates/perfiles/updProfesor.html
{% extends "base.html" %}
{% block title %}
	Actualizar
{% endblock title %}
{% block contenido %}
	<div class="page-header">
		<h4>
			<a href="{% url 'perfiles_app:profesor' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Actualizar</b>
		</h4>
	</div>
	<div>
		<form method="POST">{% csrf_token %}
			{{form.as_p}}
			 <button type="submit/button" class="btn btn-success pull-right">Guardar cambios<span class="glyphicon glyphicon-chevron-right"></span></button>
		</form>
	</div><br><br><br>
{% endblock contenido %}