apps/matricula/urls.py
from django.conf.urls import url


urlpatterns = [
  	url(r'^$', 'apps.matricula.views.main', name='main'),   	
   	url(r'^matricula$', 'apps.matricula.views.matricula', name='matricula'),
   	url(r'^matricula/add$', 'apps.matricula.views.addMatricula', name='addMatricula'),
   	
   	url(r'^curso$','apps.matricula.views.curso', name='curso'),
   	url(r'^curso/add$','apps.matricula.views.addCurso', name='addCurso'),
   	url(r'^curso/upd/(?P<id>\d+)$','apps.matricula.views.updCurso', name='updCurso'),
   	url(r'^curso/del/(?P<id>\d+)$', 'apps.matricula.views.delCurso', name='delCurso'),

   	#url(r'^guardarevento$', 'apps.agenda.views.guardarEvento'),
]

apps/perfiles/urls.py
from django.conf.urls import url


urlpatterns = [
  	url(r'^$', 'apps.perfiles.views.alumno', name='alumno'),   	
   	url(r'^addAlumno$', 'apps.perfiles.views.addAlumno', name='addAlumno'),
   	url(r'^alumno/upd/(?P<id>\d+)$', 'apps.perfiles.views.updAlumno', name='updAlumno'),
    url(r'^alumno/del/(?P<id>\d+)$', 'apps.perfiles.views.delAlumno', name='delAlumno'),

   	url(r'^profesor$','apps.perfiles.views.profesor',name='profesor'),
   	url(r'^profesor/add$', 'apps.perfiles.views.addProfesor', name='addProfesor'),
    url(r'^profesor/upd/(?P<id>\d+)$', 'apps.perfiles.views.updProfesor', name='updProfesor'),    
    url(r'^profesor/del/(?P<id>\d+)$', 'apps.perfiles.views.delProfesor', name='delProfesor'),
   	
   	url(r'^encargado$', 'apps.perfiles.views.encargado', name='encargado'),
   	url(r'^encargado/add$','apps.perfiles.views.addEncargado', name='addEncargado'),
   	url(r'^encargado/upd/(?P<id>\d+)$', 'apps.perfiles.views.updEncargado', name='updEncargado'),     
    url(r'^encargado/del/(?P<id>\d+)$', 'apps.perfiles.views.delEncargado', name='delEncargado'),


]

matricula/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'django.contrib.auth.views.login', {'template_name':'index.html'}, name='login'),
    url(r'^main/', include('apps.matricula.urls')),
    url(r'^matricula/', include('apps.matricula.urls', namespace='matricula_app')),
    url(r'^perfiles/', include('apps.perfiles.urls', namespace='perfiles_app')),
    url(r'^cerrar/$', 'django.contrib.auth.views.logout_then_login',name='logout'),
    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
]

apps/matricula/models.py
# coding: utf-8
from django.db import models
from apps.perfiles.models import Alumno, Profesor


class Curso(models.Model):

    nombre = models.CharField(max_length=50)
    precio = models.CharField(max_length=4)
    descripcion = models.CharField(max_length=100)
    profesor = models.ForeignKey(Profesor)

    def __str__(self):
        return "%s | %s" % (self.nombre, self.profesor.nombres)
    
class Matricula(models.Model):
    grd = [
        ('1', 'Primero'),
        ('2', 'Segundo'),
        ('3', 'Tercero'),
        ('4','Cuarto'),
        ('5','Quinto'),
        ('6','Sexto'),
    ]
    # codigo=models.CharField(max_length=10)
    alumno = models.ForeignKey(Alumno)
    curso = models.ForeignKey(Curso)
    grado = models.CharField(choices=grd, max_length=1)
    seccion=models.CharField(max_length=1)
    fec_reserva = models.DateTimeField(auto_now_add=True)
    pago = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    fec_confirma = models.DateTimeField(verbose_name='Plazo')
    

apps/matricula/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from apps.perfiles.models import Alumno, Encargado


class AlumnoForm(forms.ModelForm):
	class Meta:
		model=Alumno
		exclude=()
		widgets={
		#'usuario':forms.TextInput(attrs={'class':'form-control'}),
		'nombres':forms.TextInput(attrs={'class':'form-control'}),
		'apellidos':forms.TextInput(attrs={'class':'form-control'}),
		'dni':forms.TextInput(attrs={'class':'form-control'}),
		#'sexo':forms.TextInput(attrs={'class':'form-control'}),
		'lugar_nac':forms.TextInput(attrs={'class':'form-control'}),
		'direccion':forms.TextInput(attrs={'class':'form-control'}),
		'ciudad':forms.TextInput(attrs={'class':'form-control'}),
		'provincia':forms.TextInput(attrs={'class':'form-control'}),
		'telefono':forms.TextInput(attrs={'class':'form-control'}),
		'email':forms.TextInput(attrs={'class':'form-control'}),
		#'imagen':forms.FileInput(attrs={'class':'btn btn-warning'}),
		}
		
class EncargadoForm(forms.ModelForm):
	class Meta:
		model=Encargado
		exclude=()
		widgets={
		'nombres':forms.TextInput(attrs={'class':'form-control'}),
		'apellidos':forms.TextInput(attrs={'class':'form-control'}),
		'dni':forms.TextInput(attrs={'class':'form-control'}),
		'direccion':forms.TextInput(attrs={'class':'form-control'}),
		'telefono':forms.TextInput(attrs={'class':'form-control'}),
		'email':forms.EmailInput(attrs={'class':'form-control'}),
		'ocupacion':forms.TextInput(attrs={'class':'form-control'}),
		}
		

apps/matricula/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.template import RequestContext
#from django.contrib.auth.decorators import login_required
from .forms import AlumnoForm, EncargadoForm, MatriculaForm, CursoForm
from .models import Matricula, Curso


#@login_required
def main(request):
	return render(request, 'main/main.html')

#@login_required
#def matricula(request):
#	return render(request, 'matricula/matricula.html')
def matricula(request):
	lista=Matricula.objects.all()
	numreg=lista.count()
	return render(request,'matricula/matricula.html',{'lista':lista,'cantidad':numreg})

def addMatricula(request):
	if request.method=='POST':
		objform=MatriculaForm(request.POST)
		if objform.is_valid():
			objform.save()
			return redirect(reverse('matricula_app:matricula'))
	else:
		objform=MatriculaForm()		
	return render(request, 'matricula/addMatricula.html',{'form':objform})

def curso(request):
	lista=Curso.objects.all()
	numreg=lista.count()
	return render(request, 'matricula/cursos.html', {'lista':lista, 'cantidad':numreg})

def addCurso(request):
	if request.method=='POST':
		objform=CursoForm(request.POST, request.FILES)
		if objform.is_valid():
			objform.save()
			return redirect(reverse('matricula_app:curso'))
	else:
		objform=CursoForm()
	return render (request, 'matricula/addCurso.html', {'form':objform})

def updCurso(request, id):
	obj_edit=Curso.objects.get(pk=id)
	if request.method=='POST':
		objform=CursoForm(request.POST, instance=obj_edit)
		if objform.is_valid():
			objform.save()
			return redirect(reverse('matricula_app:curso'))
	else:
		objform=CursoForm(instance=obj_edit)
	return render(request, 'matricula/updCurso.html', {'form': objform}, context_instance=RequestContext(request))

def delCurso(request, id, template_name='matricula/delCurso.html'):
	objdel=Curso.objects.get(pk=id)
	if request.method=='POST':
		objdel.delete()
		return redirect(reverse('matricula_app:curso'))	
	return render(request, template_name,{'object':objdel})

templates/matricula/addCurso.html
{% extends "base.html" %}
{% block titulo %}
	Crear curso
{% endblock titulo %}
{% block contenido %}
	
<div class="page-header">
	<h4>
		<a href="{% url 'matricula_app:curso'%}" class="btn btn-warning">
			<span class="glyphicon glyphicon-chevron-left"></span>Regresar
		</a>
		<b>Datos del curso a crear</b>
	</h4>
</div>
<div>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit/button" class="btn btn-success pull-right">Registrar<span class="glyphicon glyphicon-chevron-right"></span></button>
		<a><span id="opciones">Más opciones</span></a><br>
		<a id="opcion1" href="{% url 'perfiles_app:profesor' %}"><span class="glyphicon glyphicon-plus"> Gestionar profesores</span></a>
	</form>
</div>
{% endblock contenido %}
{% block mijs %}
	<script>
	$(document).ready(function(){	    
	    $("#opcion1").hide();
	    $("#opciones").click(function(){
		    $("#opcion1").toggle();
		});	
	});
	</script>
{% endblock mijs %}

templates/matricula/addMatricula.html
{% extends "base.html" %}
{% block titulo %}
	Matricular
{% endblock titulo %}
{% block contenido %}
	
<div class="page-header">
	<h4>
		<a href="{% url 'matricula_app:matricula'%}" class="btn btn-warning">
			<span class="glyphicon glyphicon-chevron-left"></span>Regresar
		</a>
		<b>Datos del alumno a matricular</b>
	</h4>
</div>
<div>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<br>
		<button type="submit/button" class="btn btn-success pull-right">Registrar<span class="glyphicon glyphicon-chevron-right"></span></button>
		<a id="opciones"><span class="glyphicon glyphicon-chevron-right"> Más opciones</span></a><br>
		<a id="opcion1" href="{% url 'perfiles_app:alumno' %}"><span class="glyphicon glyphicon-plus"> Gestionar alumnos</span></a><br>
		<a id="opcion2" href="{% url 'matricula_app:curso' %}"><span class="glyphicon glyphicon-plus"> Gestionar cursos</span></a>
	</form>
</div>
{% endblock contenido %}

{% block mijs %}
	<script>
	$(document).ready(function(){	    
	    $("#opcion1").hide();
	    $("#opcion2").hide();
	    $("#opciones").click(function(){
		    $("#opcion1").toggle();
		    $("#opcion2").toggle();
		});	
	});
	</script>
{% endblock mijs %}

templates/matricula/cursos.html
{% extends "base.html" %}
{% block titulo %}
	Matricula
{% endblock titulo %}
{% block contenido %}
<div class="page-header">
	<h4>
		<b>Tienes <span class="label label-warning">{{cantidad}}</span> curso(s) registrados</b>
		<a href="{% url 'matricula_app:addCurso' %}" class="btn btn-primary pull-right">
			<span class="glyphicon glyphicon-plus"> Crear curso</span>
		</a>
	</h4>
</div><!-- page-header -->

<div>
	<table class="table table-striped table-condenced table-hover">
		<thead>
			<tr>
				<th>Nombre</th>
			    <th>Descripcion</th>
			    <th>Precio</th>
			    <th>Profesor</th>
			    <th>Opciones</th>
			</tr>
		</thead>
		<tbody>
		{% for curso in lista %}		
			<tr>
				<td>{{curso.nombre}}</td>
				<td>{{curso.descripcion}}</td>
				<td>{{curso.precio}}</td>
				<td>{{curso.profesor}}</td>
				<td>
					<a href="#" class="btn btn-success btn-xs"> <span class="glyphicon glyphicon-book"></span></a>
					<a href="{% url 'matricula_app:updCurso' curso.pk %}" class="btn btn-warning btn-xs"> <span class="glyphicon glyphicon-pencil"></span></a>
					<a href="{% url 'matricula_app:delCurso' curso.pk %}" class="btn btn-danger btn-xs"> <span class="glyphicon glyphicon-trash"></span></a>
				</td>
			</tr>	
		{% endfor %}
		</tbody>	
	</table>
</div>
{% endblock contenido %}

templates/matricula/delCurso.html
{% extends "base.html" %}
{% block title %}
	Confirma eliminar
{% endblock title %}
{% block contenido %}
<div class="page-header">
		<h4>
			<a href="{% url 'matricula_app:curso' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Confirma eliminar</b>
		</h4>
	</div>
	<form method="POST">{% csrf_token %}
		<div class="alert alert-danger">
		<span class="glyphicon glyphicon-exclamation-sign"></span>
		  <b>Cuidado!</b> Estas seguro de querer eliminar a: "<strong>{{ object }}</strong>" ?
		</div>		
			<button type="submit/button" class="btn btn-success pull-right">Estoy seguro<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>	

{% endblock contenido %}

templates/matricula/matricula.html
{% extends "base.html" %}
{% block titulo %}
	Matricula
{% endblock titulo %}
{% block contenido %}
	
<div class="page-header">
	<h4>
		<a href="#" class="btn btn-warning">
			<span class="glyphicon glyphicon-chevron-left"></span>Regresar
		</a>
		<strong>Datos del alumno</strong>
	</h4>
</div>
<div class="page-header">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit/button" class="btn btn-success pull-right">Registrar<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>
</div>
<div class="page-header">
<h4>
	<strong>Datos del encargado</strong>
</h4>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form1.as_p}}
		<button type="submit/button" class="btn btn-success pull-right">Registrar<span class="glyphicon glyphicon-chevron-right"></span></button>
	</form>
</div>
{% endblock contenido %}

templates/matricula/updCurso.html
{% extends "base.html" %}
{% block title %}
	Actualizar
{% endblock title %}
{% block contenido %}
	<div class="page-header">
		<h4>
			<a href="{% url 'matricula_app:curso' %}" class="btn btn-warning">
				<span class="glyphicon glyphicon-chevron-left"></span>Regresar
			</a>
			<b>Actualizar Curso</b>
		</h4>
	</div>
	<div>
		<form method="POST">{% csrf_token %}
			{{form.as_p}}
			 <button type="submit/button" class="btn btn-success pull-right">Guardar cambios<span class="glyphicon glyphicon-chevron-right"></span></button>
			<a id="opciones"><span class="glyphicon glyphicon-chevron-right"> Más opciones</span></a><br>
			<a id="opcion1" href="{% url 'perfiles_app:profesor' %}"><span class="glyphicon glyphicon-plus"> Gestionar profesores</span></a><br>
		</form>
	</div><br><br><br>
{% endblock contenido %}
{% block mijs %}
	<script>
	$(document).ready(function(){	    
	    $("#opcion1").hide();
	    $("#opciones").click(function(){
		    $("#opcion1").toggle();
		});	
	});
	</script>
{% endblock mijs %}