apps/matricula/urls.py
from django.conf.urls import url


urlpatterns = [
  	url(r'^$', 'apps.matricula.views.main', name='main'),   	
   	url(r'^matricula$', 'apps.matricula.views.matricula', name='matricula'),
   	url(r'^matricula/add$', 'apps.matricula.views.addMatricula', name='addMatricula'),
   	
   	url(r'^curso$','apps.matricula.views.curso', name='curso'),
   	url(r'^curso/add$','apps.matricula.views.addCurso', name='addCurso'),
   	url(r'^curso/upd/(?P<id>\d+)$','apps.matricula.views.updCurso', name='updCurso'),
   	url(r'^curso/del/(?P<id>\d+)$', 'apps.matricula.views.delCurso', name='delCurso'),

   	#url(r'^guardarevento$', 'apps.agenda.views.guardarEvento'),
]

apps/perfiles/urls.py
from django.conf.urls import url


urlpatterns = [
  	url(r'^$', 'apps.perfiles.views.alumno', name='alumno'),   	
   	url(r'^addAlumno$', 'apps.perfiles.views.addAlumno', name='addAlumno'),
   	url(r'^alumno/upd/(?P<id>\d+)$', 'apps.perfiles.views.updAlumno', name='updAlumno'),
    url(r'^alumno/del/(?P<id>\d+)$', 'apps.perfiles.views.delAlumno', name='delAlumno'),

   	url(r'^profesor$','apps.perfiles.views.profesor',name='profesor'),
   	url(r'^profesor/add$', 'apps.perfiles.views.addProfesor', name='addProfesor'),
    url(r'^profesor/upd/(?P<id>\d+)$', 'apps.perfiles.views.updProfesor', name='updProfesor'),    
    url(r'^profesor/del/(?P<id>\d+)$', 'apps.perfiles.views.delProfesor', name='delProfesor'),
   	
   	url(r'^encargado$', 'apps.perfiles.views.encargado', name='encargado'),
   	url(r'^encargado/add$','apps.perfiles.views.addEncargado', name='addEncargado'),
   	url(r'^encargado/upd/(?P<id>\d+)$', 'apps.perfiles.views.updEncargado', name='updEncargado'),     
    url(r'^encargado/del/(?P<id>\d+)$', 'apps.perfiles.views.delEncargado', name='delEncargado'),


]

matricula/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'django.contrib.auth.views.login', {'template_name':'index.html'}, name='login'),
    url(r'^main/', include('apps.matricula.urls')),
    url(r'^matricula/', include('apps.matricula.urls', namespace='matricula_app')),
    url(r'^perfiles/', include('apps.perfiles.urls', namespace='perfiles_app')),
    url(r'^cerrar/$', 'django.contrib.auth.views.logout_then_login',name='logout'),
    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT,}),
]

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Demo matricula</title>
<link rel="stylesheet" href="{% static "css/admin-style.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
{% block estilos %}
  
{% endblock estilos %}
</head>

<body>

<div class="wrapper">
  <header>
    <div class="left">
      <button id="menu" title="Menu"><span class="glyphicon glyphicon-list"></span></button>     
      <h1>Sistema de matriculas</h1>
    </div>
    <div class="utils right"> 
      <a href="">.</a>
      <a href="{% url 'matricula_app:main' %}" class='alerts'><span class="glyphicon glyphicon-home"></span></a> <i class="sep">&nbsp;</i> 
      <a href="#" class='alerts'><span class="glyphicon glyphicon-grain"></span></a> <i class="sep">&nbsp;</i> 
      <a > <b><span class="glyphicon glyphicon-user"> {{ user.username|capfirst }}</span></b></a> <i class="sep">&nbsp;</i>
      <a >.</a>
      <a href="{%url 'logout'%}"><i class="glyphicon glyphicon-off"></i></a>         
      <a >.</a>
    </div>

  </header>
  <!--//Header-->
  <div class="content">
    <aside>
      <h2>Site Logo</h2>
      <div class="controls">
        <input type="search" id="search" name="search" />
        <label for="search"><i class="fa fa-search"></i></label>
      </div>
      <nav class='site-nav'> 
      <a class="active" href="{% url 'matricula_app:main' %}"><span class="glyphicon glyphicon-home"></span> Home</a>
      <a href="{% url 'matricula_app:matricula' %}"><span class="glyphicon glyphicon-tasks"></span> Matricular</a> 
      <a href="{% url 'perfiles_app:encargado' %}"><span class="glyphicon glyphicon-envelope"></span> Contact/Family</a> 
      <a href="{% url 'perfiles_app:profesor' %}"><span class="glyphicon glyphicon-user"></span> Profesor</a> 
      <a href="{% url 'matricula_app:curso' %}"><i class="glyphicon glyphicon-book"></i> Cursos</a> </nav>
      <footer> <a href="{%url 'logout'%}"><i class="glyphicon glyphicon-off"></i> Logout</a> </footer>
    </aside>
    <!--//sidebar-->
    <section>
      <article>
      <div class="container">
        {% block contenido %}
          
        {% endblock contenido %}
      </div>
      </article>
    </section>
    <div class="site-footer">
      <div class="right"> <a href="">Terms of Use</a> <span class="sep"></span> <a href="" class='feedback'><i class="fa fa-bullhorn"></i> Feedback</a> </div>
    </div>
    <!--//body content--> 
  </div>
  <!--//Main Content--> 
</div>
<script src="{% static "js/jquery-1.11.3.js" %}"></script> 
<script src="{% static "js/menu.js" %}"></script>
<script>
  $(function(){
  $("#menu").on("click" , function(){
    $(this).toggleClass("active");
    $("body").toggleClass("nav-open");
  });
});
</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% block mijs %}
  
{% endblock mijs %}
</body>
</html>

templates/index.html
{%load staticfiles%}
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>Pure CSS Blurred Video Background Login Box. (fork)</title>    
    
        <link rel="stylesheet" href="{% static "css/style.css" %}">    
    
  </head>

  <body>

  <div class="vid-container">
  <video id="Video1" class="bgvid back" autoplay="false" muted="muted" preload="auto" loop>
      <source src="http://shortcodelic1.manuelmasiacsasi.netdna-cdn.com/themes/geode/wp-content/uploads/2014/04/milky-way-river-1280hd.mp4.mp4" type="video/mp4">
  </video>
  <div class="inner-container">
    <video id="Video2" class="bgvid inner" autoplay="false" muted="muted" preload="auto" loop>
      <source src="http://shortcodelic1.manuelmasiacsasi.netdna-cdn.com/themes/geode/wp-content/uploads/2014/04/milky-way-river-1280hd.mp4.mp4" type="video/mp4">
    </video>
    <div class="box">
      <form method="post">
      {% csrf_token %}
        <h1>Login</h1>
        <input type="text" id="username" name="username" placeholder="Username"/>
        <input type="password" name="password" id="password" placeholder="Password"/>
        <button type="submit">Login</button>
        <p>Not a member? <span>Sign Up</span></p>
      </form>
    </div>
  </div>
</div>
<!--  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

<script src="js/index.js"></script> -->

    
    
    
  </body>
</html>